spring.application.name=booking-system2

spring.datasource.url=jdbc:mysql://localhost:3306/booking_system
spring.datasource.username=root
spring.datasource.password= Arman1231123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
